Update update_report.yml

diff --git a/.github/workflows/update_report.yml b/.github/workflows/update_report.yml
--- a/.github/workflows/update_report.yml
+++ b/.github/workflows/update_report.yml
@@ -1,44 +1,36 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-     branches:
-     # Default branches below
-       - main
-       - master
+    paths: ['**.Rmd']
+
+name: render-rmarkdown
 
 jobs:
-  render_document:
-    runs-on: macos-10.15 # macOS Catalina
-    strategy:
-      matrix:
-        r-version: [4.0.2] 
+  render-rmarkdown:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - name: Set up Git repository
+      - name: Checkout repo
         uses: actions/checkout@v2
-      - name: Set up R ${{ matrix.r-version }}
-        uses: r-lib/actions/setup-R@v1
         with:
-          r-version: ${{ matrix.r-version }}
-      - name: Setting up pandoc for Rmd docs
-        uses: r-lib/actions/setup-pandoc@v1
-      - name: Install dependencies
+          fetch-depth: 0
+
+      - uses: r-lib/actions/setup-pandoc@v1
+
+      - uses: r-lib/actions/setup-r@v1
+
+      - uses: r-lib/actions/setup-renv@v1
+      
+      - name: Render Rmarkdown files
         run: |
-          Rscript -e 'install.packages(c("dplyr", "rmarkdown"))'
-	  Rscript -e 'rmarkdown::render("report.Rmd", "html_document")'
-      # - name: Updating data and cleaning 
-      #  run: |
-      #    source('scripts/datacleaning.R')
-      #  shell: Rscript {0}
-      - name: Commit files
+          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+
+      - name: Commit results
         run: |
-          git config --local core.autocrlf false
-          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
-          git config --local user.name "${{ github.actor }}"
-          git add . && git add --renormalize .
-          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
-          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
-          NO_PAGER=1 git --no-pager diff HEAD^
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          branch: ${{ github.head_ref }}
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
